/*---------------------------------------------------------------------------
 * Please note:
 *   This file is generated by scons. All changes will be lost!
 --------------------------------------------------------------------------*/


#ifndef __VERSION_H__
#define __VERSION_H__


#define VERSION_MAJ ${PROJECT_VERSION_MAJ}
#define VERSION_MIN ${PROJECT_VERSION_MIN}
#define VERSION_VCS "${PROJECT_VERSION_VCS}"
#define VERSION_ALL "${PROJECT_VERSION_MAJ}.${PROJECT_VERSION_MIN}.${PROJECT_VERSION_VCS}"


#endif  /* __VERSION_H__ */

