/*---------------------------------------------------------------------------
 * Please note:
 *   This file is generated by scons. All changes will be lost!
 --------------------------------------------------------------------------*/


#ifndef __VERSION_H__
#define __VERSION_H__


#define VERSION_MAJ ${PROJECT_VERSION_MAJOR}
#define VERSION_MIN ${PROJECT_VERSION_MINOR}
#define VERSION_VCS "${PROJECT_VERSION_VCS}"
#define VERSION_ALL "${PROJECT_VERSION_ALL}"


#endif  /* __VERSION_H__ */

